# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'bubble-wrap'
require 'bubble-wrap/location'
require 'bubble-wrap/core'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'runMe'
  app.identifier = 'com.example.mattsprofile.mattsnewapp'
  app.info_plist['NSAppTransportSecurity'] = { 'NSAllowsArbitraryLoads' => true }
  app.frameworks += ['CoreData', 'CoreLocation']
  app.info_plist['NSLocationWhenInUseUsageDescription'] = 'Description.'
  app.info_plist['NSLocationAlwaysUsageDescription'] = 'Description.'
end
